laravel/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

/* Api */
Route::group(['prefix' => 'api', 'namespace' => 'Api'], function () {
    // Users
    Route::controller('geo-location', 'GeoLocationController');
});

/* Resources */
Route::group(['namespace' => 'Resources'], function () {
    // Users
    Route::resource('users', 'UsersController');

    // Claims

    Route::post('claims/{id}/update-info', ['as' => 'claims.update-info', 'uses' => 'ClaimsController@updateInfo']);
    Route::post('claims/{id}/update-description', ['as' => 'claims.update-description', 'uses' => 'ClaimsController@updateDescription']);
    Route::post('claims/{id}/update-ike', ['as' => 'claims.update-ike', 'uses' => 'ClaimsController@updateIke']);

    Route::get('claims/{id}/{status}', ['as' => 'claims.status', 'uses' => 'ClaimsController@show']);

    Route::post('claims/{id}/verification/approve', ['as' => 'claims.dataVerification.approve', 'uses' => 'Claim\DataVerificationController@approve']);
    Route::post('claims/{id}/verification/cancel', ['as' => 'claims.dataVerification.cancel', 'uses' => 'Claim\DataVerificationController@cancel']);

    Route::post('claims/{id}/report/confirm', ['as' => 'claims.dataReport.confirm', 'uses' => 'Claim\DataReportController@confirm']);

    Route::post('claims/{id}/processing/confirm', ['as' => 'claims.processing', 'uses' => 'ClaimsController@processing']);
    Route::post('claims/{id}/finished/confirm', ['as' => 'claims.finished', 'uses' => 'ClaimsController@finished']);

    // Insured claim view
    Route::get('/insured', ['as' => 'claims.public.login', 'uses' => 'ClaimsController@publicLogin']);
    Route::post('/insured', ['as' => 'claims.public.login', 'uses' => 'ClaimsController@postPublicLogin']);

    Route::resource('claims', 'ClaimsController');
    Route::resource('claims.dataIke', 'Claim\DataIkeController');
    Route::resource('claims.dataContact', 'Claim\DataContactController');
    Route::resource('claims.dataVerification', 'Claim\DataVerificationController');
    Route::resource('claims.dataVisits', 'Claim\DataVisitsController');
    Route::resource('claims.dataPreliminary', 'Claim\DataPreliminaryController');
    Route::resource('claims.dataReport', 'Claim\DataReportController');
    Route::resource('claims.damageAssessment', 'Claim\DamageAssessmentController');
    Route::resource('claims.contacts', 'Claim\ContactsController');
    Route::resource('claims.notes', 'Claim\NotesController');
    Route::resource('claims.documents', 'Claim\DocumentsController');
    Route::resource('claims.addresses', 'Claim\AddressesController');
    Route::resource('claims.surveys', 'Claim\SurveysController');
    Route::resource('claims.checkList', 'Claim\CheckListAnswersController');
    Route::resource('claims.statuses', 'Claim\StatusesController', ['only' => 'store']);

    // Stats
    Route::get('stats/users', ['as' => 'stats.users', 'uses' => 'StatsController@users' ]);
    Route::get('stats/external', ['as' => 'stats.external', 'uses' => 'StatsController@external' ]);
    Route::get('stats/get-claims', ['as' => 'stats.get-claims', 'uses' => 'StatsController@getClaims' ]);
    Route::get('stats/claims-cities', ['as' => 'stats.claims-cities', 'uses' => 'StatsController@claimsByCities' ]);
    Route::get('stats/claims-stats', ['as' => 'stats.claims-stats', 'uses' => 'StatsController@claimsStats' ]);
    Route::resource('stats', 'StatsController');
});

// Dashboard
Route::get('dashboard', ['as' => 'dashboard.index', 'uses' => 'DashboardController@getIndex']);

// Authentication routes...
Route::get('auth/logout', ['as' => 'auth.logout', 'uses' => 'Auth\AuthController@getLogout']);
Route::get('/', ['as' => 'auth.login', 'uses' => 'Auth\AuthController@getLogin']);
Route::post('/', ['as' => 'auth.login', 'uses' => 'Auth\AuthController@postLogin']);

// Insured claim view
Route::get('/insured', ['as' => 'public.login', 'uses' => 'Resources\PublicClaimsController@publicLogin']);
Route::post('/insured', ['as' => 'public.login', 'uses' => 'Resources\PublicClaimsController@postPublicLogin']);
Route::get('/insured/{hash}', ['as' => 'public.index', 'uses' => 'Resources\PublicClaimsController@publicClaim']);

laravel/app/Http/Controllers/Resources/Claim/AddressesController.php
<?php

namespace App\Http\Controllers\Resources\Claim;

use App\Events\ClaimWasUpdated;
use App\Http\Requests\Claim\AddressesStorePostRequest;
use App\Models\Address;
use App\Models\Claim;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class AddressesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param AddressesStorePostRequest|Request $request
     * @param $claimId
     * @return \Illuminate\Http\Response
     */
    public function store(AddressesStorePostRequest $request, $claimId)
    {
        $claim = Claim::findOrFail($claimId);

        // Store Address
        $address = new Address($request->input('claim.address'));
        $claim->address()->save($address);

        // Fire event
        // event(new ClaimWasUpdated($claim));

        return back()->with('messages.success', [trans('global.The address has been saved successfully')]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param AddressesStorePostRequest|Request $request
     * @param $claimId
     * @param $addressId
     * @return \Illuminate\Http\Response
     * @internal param int $id
     */
    public function update(AddressesStorePostRequest $request, $claimId, $addressId)
    {
        // Get Claim
        $claim = Claim::findOrFail($claimId);

        // Get Address
        $address = Address::findOrFail($addressId);

        // Update Address
        $address->fill($request->input('claim.address'));

        // Save Address
        $claim->address()->save($address);

        event(new ClaimWasUpdated($claim, ['type' => 'address', 'value' => $address]));

        return back()->with('messages.success', [trans('global.The address has been updated successfully')]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

laravel/app/Http/Controllers/Resources/Claim/CheckListAnswersController.php
<?php

namespace App\Http\Controllers\Resources\Claim;

use App\Models\CheckListAnswer;
use App\Models\Claim;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class CheckListAnswersController extends Controller
{
    /**
     * Store a newly created resource in storage.
     *
     * @param AddressesStorePostRequest|Request $request
     * @param $claimId
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, $claimId)
    {
        // Get Claim
        $claim = Claim::findOrFail($claimId);

        // Parse Date
        $answers = $request->input('claim.check_list');

        if (count($answers) == \App\Models\CheckListQuestion::all()->count()) {
            \DB::table('check_list_answers')->where('claim_id', $claim->id)->delete();
            foreach ($answers as $questionId => $answer) {
                $a = new CheckListAnswer(['claim_id' => $claim->id, 'question_id' => $questionId, 'answer' => $answer]);
                $claim->checkListAnswers()->save($a);
            }
            return back()->with('messages.success', [trans('global.The survey has been saved successfully')]);
        }
        else {
            return back()->with('messages.success', [trans('global.Missing data')]);
        }
    }
}

laravel/app/Http/Controllers/Resources/Claim/ContactsController.php
<?php

namespace App\Http\Controllers\Resources\Claim;

use App\Events\ClaimWasUpdated;
use App\Http\Requests\Claim\ContactsStorePostRequest;
use App\Http\Requests\Claim\ContactsUpdatePostRequest;
use App\Models\Claim;
use App\Models\Contact;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class ContactsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @param $claimId
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, $claimId)
    {
        $claim = Claim::findOrFail($claimId);

        // Store Contact
        $contact = new Contact($request->input('claim.contact'));
        $claim->contacts()->save($contact);

        // Fire event
        event(new ClaimWasUpdated($claim, ['type' => 'contact', 'value' => $contact, 'add' => TRUE]));

        return back()->with('messages.success', [trans('global.The contact has been created successfully')]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $claimId
     * @param  int $contactId
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $claimId, $contactId)
    {
        // Get Claim
        $claim = Claim::findOrFail($claimId);

        // Get Contact
        $contact = Contact::findOrFail($contactId);
        $contact->fill($request->input('claim.contact'));

        // Store Contact
        $claim->contacts()->save($contact);

        // Fire event
        event(new ClaimWasUpdated($claim, ['type' => 'contact', 'value' => $contact]));

        return back()->with('messages.success', [trans('global.The contact has been updated successfully')]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

laravel/app/Http/Controllers/Resources/Claim/DamageAssessmentController.php
<?php

namespace App\Http\Controllers\Resources\Claim;

use App\Models\Claim;
use App\Models\DamageAssessment;
use App\Models\Status;
use App\Models\Activity;
use Illuminate\Http\Request;
use Carbon\Carbon;
use Illuminate\Support\Facades\Auth;
use App\Events\ClaimWasUpdated;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class DamageAssessmentController extends Controller
{
    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @param $claimId
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, $claimId)
    {
        // Validate
        $this->validate($request, [
            'claim.damage_assessment.amount_loss' => ['required'],
            'claim.damage_assessment.deductible' => ['required'],
            'claim.damage_assessment.adjustment_description' => ['required'],
        ]);

        // Get Claim
        $claim = Claim::findOrFail($claimId);

        // Parse Data
        $damageAssessmentData = $request->input('claim.damage_assessment');
        $amount_loss = str_replace(',','.',$damageAssessmentData['amount_loss']);
        $deductible = str_replace(',','.',$damageAssessmentData['deductible']);
        $damageAssessmentData['amount_loss'] = $amount_loss;
        $damageAssessmentData['deductible'] = $deductible;
        $claim->damageAssessments()->save(new DamageAssessment($damageAssessmentData));

        // If a damage assessment is added after the report
        // has been confirmed, notify it with an activity
        if ($claim->status->id >= Status::REPORT) {
            event(new ClaimWasUpdated($claim, ['type' => 'damage assessment', 'add' => TRUE]));
        }

        return back()->with('messages.success', [trans('global.The damage assessment has been saved successfully')]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request $request
     * @param  int $claimId
     * @param  int $damageAssessmentId
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $claimId, $damageAssessmentId)
    {
        // Validate
        $this->validate($request, [
            'claim.damage_assessment.amount_loss' => ['required'],
            'claim.damage_assessment.deductible' => ['required'],
            'claim.damage_assessment.adjustment_description' => ['required'],
        ]);

        // Get Claim
        $claim = Claim::findOrFail($claimId);
        $damageAssessment = DamageAssessment::findOrFail($damageAssessmentId);

        // Parse Data
        $damageAssessmentData = $request->input('claim.damage_assessment');
        $damageAssessment->fill($damageAssessmentData);
        $claim->damageAssessments()->save($damageAssessment);

        // If a damage assessment is updated after the report
        // has been confirmed, notify it with an activity
        if ($claim->status->id >= Status::REPORT) {
            event(new ClaimWasUpdated($claim, ['type' => 'damage assessment']));
        }

        return back()->with('messages.success', [trans('global.The damage assessment has been updated successfully')]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request $request
     * @param  int $claimId
     * @param  int $damageAssessmentId
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $claimId, $damageAssessmentId)
    {
        // Get Claim
        $claim = Claim::findOrFail($claimId);
        $damageAssessment = DamageAssessment::findOrFail($damageAssessmentId);
        $damageAssessment->delete();

        // If a damage assessment is updated after the report
        // has been confirmed, notify it with an activity
        if ($claim->status->id >= Status::REPORT) {
            event(new ClaimWasUpdated($claim, ['type' => 'damage assessment', 'delete' => TRUE]));
        }

        return back()->with('messages.success', [trans('global.The damage assessment has been deleted successfully')]);
    }
}

laravel/app/Http/Controllers/Resources/Claim/DataContactController.php
<?php

namespace App\Http\Controllers\Resources\Claim;

use App\Events\ClaimVisitDateWasSet;
use App\Http\Requests\Claim\AddressesStorePostRequest;
use App\Models\Claim;
use App\Models\DataContact;
use App\Models\Activity;
use App\Models\Status;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class DataContactController extends Controller
{
    /**
     * Store a newly created resource in storage.
     *
     * @param AddressesStorePostRequest|Request $request
     * @param $claimId
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, $claimId)
    {
        // Validate
        $this->validate($request, [
            'claim.contact.contact' => ['required', 'in:yes,no'],
            'claim.contact.visit_date' => ['required', 'date_format:d/m/Y H:i'],
            'claim.contact.note' => ['required'],
        ]);

        // Get Claim
        $claim = Claim::findOrFail($claimId);

        // Parse Date
        $inputContact = $request->input('claim.contact');

        $date = Carbon::createFromFormat('d/m/Y H:i', $inputContact['visit_date']);
        $inputContact = array_merge($inputContact, ['visit_date' => $date]);

        // Store Ike
        $dataContact = new DataContact($inputContact);
        $claim->dataContact()->save($dataContact);

        // Create Activity
        $activity = new Activity([
            'activity' => 'contact',
            'date' => Carbon::now(),
            'attachment' => $dataContact->id,
            'claim_id' => $claim->id,
            'user_id' => Auth::user()->id]);
        $claim->activities()->save($activity);

        // Fire event
        if ($inputContact['contact'] == 'yes') {
            if ($claim->status->id == Status::VERIFICATION) {
                $status = Status::find(Status::CONTACT);
                $claim->statuses()->save($status);

                $claim->last_status = $status->id;
                $claim->save();
            }
        }

        return back()->with('messages.success', [trans('global.The contact data has been saved successfully')]);
    }
}

laravel/resources/views/resources/claims/notes/create.blade.php
@extends('resources.claims.notes.modal', [
    'action' => route('claims.notes.store', $claim),
    'section' => 'modal-body-notes-create'
])

@section('modal-body-notes-create')
    @include('resources.claims.notes.form', [
        'bagName' => 'claim_notes',
        'note' => old('note'),
        'visibility' => old('visibility'),
        'description' => old('description'),
        'hasAttachment' => !empty(old('attachmentName')),
        'attachmentName' => old('attachmentName')
    ])
@endsection

laravel/resources/views/resources/claims/notes/edit.blade.php
@extends('resources.claims.notes.modal', [
    'modalId' => 'modal-claims-notes-' . $note->id,
    'action' => route('claims.notes.update', [$claim, $note]),
    'section' => 'modal-body-notes-edit-' . $note->id
])

@section('modal-body-notes-edit-' . $note->id)
    {!! method_field('PUT') !!}
    @include('resources.claims.notes.form', [
        'bagName' => 'claim_notes',
        'note' => $note,
        'visibility' => old('visibility', $note->visibilities()->getResults()),
        'description' => old('description', $note->description),
        'hasAttachment' => !empty(old('attachmentName', $note->attachmentName)),
        'attachmentName' => old('attachmentName', $note->attachmentName)
    ])
@endsection

laravel/resources/views/resources/claims/notes/form.blade.php
<div class="row">

    <div class="col-md-12">
        <div class="form-group {!! $errors->{$bagName}->first('description') ? 'has-error' : '' !!}">
            <label class="control-label" for="about">{!! trans('global.Note') !!}</label>
            <textarea rows="3" class="form-control autogrow" name="description" data-validate="required"
                      placeholder="{!! trans('global.Note') !!}">{!! $description !!}</textarea>
        </div>
    </div>

    <div class="col-md-12">
        <div class="form-group {!! $errors->{$bagName}->first('attachmentName') ? 'has-error' : '' !!}">
            <label class="control-label" for="about">{!! trans('global.Attachment') !!}</label>
            @if($hasAttachment)
                <div class="current-attachment">
                    <i class="fa fa-file"></i> <span>{!! $attachmentName !!}</span>
                    <div class="row">
                        <div class="col-md-12">
                            <a class="btn btn-xs btn-default" href="{!! '/static/' . $note->attachmentHash . '-' . $note->attachmentName !!}" download target="_blank">
                                <i class="fa fa-download"></i>
                                {!! trans('global.Download') !!}
                            </a>
                            <a class="btn btn-xs btn-default remove-attachment" href="javascript:;">
                                <i class="fa fa-times"></i>
                                {!! trans('global.Delete') !!}
                            </a>
                            <input id="note-attachment" class="hidden" type="text" name="attachment" value="{!! $attachmentName !!}">
                        </div>
                    </div>
                </div>
            @endif
            <input id="note-attachment" class="@if($hasAttachment) hidden @endif" type="file" name="attachment">
        </div>
    </div>

    @if(isset(Illuminate\Support\Facades\Auth::user()->id))
    <div class="form-group">
        <div class="col-sm-12">
            <label>{!! trans('global.Visibility') !!}</label>
            @foreach(\App\Models\Role::getRoles() as $role)
            <div class="checkbox">
                <label>
                    <input type="checkbox" name="visibility[{!! $role->id !!}]"
                    @if(isset($note))
                        @if($note->noteIsVisibleForUser($role->id))
                            checked
                        @endif
                    @else
                        checked
                    @endif
                    >
                    {!! $role->name !!}
                </label>
            </div>
            @endforeach
            <div class="checkbox">
                <label>
                    <input type="checkbox" name="visibility[0]"
                    @if(isset($note) && $note->noteIsVisibleForUser(null))
                        checked
                    @endif
                    >
                    {!! trans('global.Insured') !!}
                </label>
            </div>
        </div>
    </div>
    @endif

</div>

laravel/resources/views/resources/claims/notes/index.blade.php
<div class="panel panel-default">
    <div class="panel-heading">
        {!! trans('global.Notes') !!}
        <div class="panel-options">
            <a class="btn btn-single btn-gray" href="javascript:" data-toggle="modal"
               data-target="#modal-claims-notes">
                {!! trans('global.Add New Note') !!}
            </a>
        </div>
    </div>

    <div class="panel-body">
        <!-- Show -->
        @include('resources.claims.notes.notes-list', [
            'userRoleId'  => isset(Illuminate\Support\Facades\Auth::user()->id) ? Illuminate\Support\Facades\Auth::user()->id : null
        ])

         <!-- Modal -->
        @include('resources.claims.notes.create')
    </div>
</div>

laravel/resources/views/resources/claims/notes/modal-delete.blade.php
<div class="modal fade" id="modal-note-delete-{!! $note->id !!}">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">{!! trans('global.Delete') !!} {!! trans('global.Note') !!}</h4>
            </div>

            <div class="modal-body">
                <p>{!! trans('global.Are you sure you want to delete this?') !!}</p>
            </div>

            <div class="modal-footer">
                <form method="POST" action="{!! route('claims.notes.destroy', [$claim, $note]) !!}">
                    {!! csrf_field() !!}
                    {!! method_field('DELETE') !!}
                    <button type="button" class="btn btn-white" data-dismiss="modal">
                        {!! trans('global.Close') !!}
                    </button>
                    <button type="submit" class="btn btn-danger">
                        {!! trans('global.Delete') !!}
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>

laravel/resources/views/resources/claims/notes/modal-response.blade.php
<div class="modal {!! $errors->claim_notes->isEmpty() ? '' : 'js-modal-error' !!}">
    <div class="modal-dialog">
        <div class="modal-content">
            <form role="form" method="POST" action="{!! session('formResponse')['route'] !!}"
                  class="validate" novalidate>
                {!! csrf_field() !!}
                {!! method_field(session('formResponse')['method']) !!}

                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">{!! trans('global.Create New Note') !!}</h4>
                </div>

                <div class="modal-body">

                    @include('resources.claims.notes.form', [
                        'bagName' => 'claim_notes',
                        'description' => old('description'),
                        'attachment' => old('attachment')
                    ])

                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-white" data-dismiss="modal">
                        {!! trans('global.Close') !!}
                    </button>
                    <button type="submit" class="btn btn-success">
                        {!! trans('global.Create') !!}
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

laravel/resources/views/resources/claims/notes/modal.blade.php
 <div class="modal {!! old('modal_old') == (!empty($modalId) ? $modalId : 'modal-claims-notes') ? 'modal_old' : '' !!}"
     id="{!! !empty($modalId) ? $modalId : 'modal-claims-notes'!!}">
    <div class="modal-dialog">
        <div class="modal-content">

            <form role="form" method="POST" action="{!! $action !!}" class="validate" enctype="multipart/form-data" novalidate>
                {!! csrf_field() !!}
                <input type="hidden" name="modal_old"
                       value="{!! !empty($modalId) ? $modalId : 'modal-claims-notes'!!}">

                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">{!! trans('global.Notes') !!}</h4>
                </div>

                <div class="modal-body">
                    @yield($section)
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-white" data-dismiss="modal">
                        {!! trans('global.Close') !!}
                    </button>
                    <button type="submit" class="btn btn-success">
                        {!! trans('global.Save') !!}
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

laravel/resources/views/resources/claims/notes/notes-list.blade.php
<table class="table table-hover members-table middle-align notes-table">
    <thead>
    <tr>
        <th>{!! trans('global.Name') !!}</th>
        <th>{!! trans('global.Date') !!}</th>
        <th>{!! trans('global.Note') !!}</th>
        <th>{!! trans('global.Attachment') !!}</th>
        <th>{!! trans('global.Options') !!}</th>
    </tr>
    </thead>
    <tbody>
    @if($claim->notes->isEmpty())
        <tr style="text-align: center">
            <td colspan="5">
                <strong>{!! trans('global.No Notes') !!}</strong>. {!! trans('global.Please create new note') !!}.
            </td>
        </tr>
    @else
        @if($claim->thereIsAVisibleNoteForUser($userRoleId))
        @foreach($claim->notes as $note)
            @if($note->noteIsVisibleForUser($userRoleId))
            <tr>
                <td>
                    @if($note->user != null)
                        {!! $note->user->name !!}
                    @else
                        {!! trans('global.Insured') !!}
                    @endif
                </td>
                <td>
                    {!! $note->date !!}
                </td>
                <td class="note-description">
                    {!! $note->description !!}
                </td>
                <td class="note-attachment">
                    @if(!empty($note->attachmentName))
                        <a href="{!! '/static/' . $note->attachmentHash . '-' . $note->attachmentName !!}" target="_blank"><i class="fa fa-search"></i>
                        <a href="{!! '/static/' . $note->attachmentHash . '-' . $note->attachmentName !!}" download target="_blank"><i class="fa fa-download"></i>
                    @else
                        -
                    @endif
                </td>
                <td>
                    @if( (Illuminate\Support\Facades\Auth::guest() && $note->user == null) ||
                         (!Illuminate\Support\Facades\Auth::guest() && $note->user != null && Illuminate\Support\Facades\Auth::user()->id == $note->user->id) ||
                         (!Illuminate\Support\Facades\Auth::guest() && Illuminate\Support\Facades\Auth::user()->id == \App\Models\Role::SUPER_ADMIN) ||
                         (!Illuminate\Support\Facades\Auth::guest() && Illuminate\Support\Facades\Auth::user()->id == \App\Models\Role::COORDINADOR) )
                    <a class="btn btn-xs btn-default" href="#" data-toggle="modal"
                       data-target="#modal-claims-notes-{!! $note->id !!}">
                        <i class="fa fa-pencil"></i>
                        {!! trans('global.Edit') !!}
                    </a>
                    @include('resources.claims.notes.edit')
                    <a class="btn btn-xs btn-default" href="#" data-toggle="modal"
                       data-target="#modal-note-delete-{!! $note->id !!}">
                        <i class="fa fa-remove"></i>
                        {!! trans('global.Delete') !!}
                    </a>
                    @include('resources.claims.notes.modal-delete')
                    @endif
                </td>
            </tr>
            @endif
        @endforeach
        @else
            <tr style="text-align: center">
                <td colspan="5">
                    <strong>{!! trans('global.No available notes') !!}</strong>.
                </td>
            </tr>
        @endif
    @endif
    </tbody>
</table>