laravel/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

/* Api */
Route::group(['prefix' => 'api', 'namespace' => 'Api'], function () {
    // Users
    Route::controller('geo-location', 'GeoLocationController');
});

/* Resources */
Route::group(['namespace' => 'Resources'], function () {
    // Users
    Route::resource('users', 'UsersController');

    // Claims

    Route::post('claims/{id}/update-info', ['as' => 'claims.update-info', 'uses' => 'ClaimsController@updateInfo']);
    Route::post('claims/{id}/update-description', ['as' => 'claims.update-description', 'uses' => 'ClaimsController@updateDescription']);
    Route::post('claims/{id}/update-ike', ['as' => 'claims.update-ike', 'uses' => 'ClaimsController@updateIke']);

    Route::get('claims/{id}/{status}', ['as' => 'claims.status', 'uses' => 'ClaimsController@show']);

    Route::post('claims/{id}/verification/approve', ['as' => 'claims.dataVerification.approve', 'uses' => 'Claim\DataVerificationController@approve']);
    Route::post('claims/{id}/verification/cancel', ['as' => 'claims.dataVerification.cancel', 'uses' => 'Claim\DataVerificationController@cancel']);

    Route::post('claims/{id}/report/confirm', ['as' => 'claims.dataReport.confirm', 'uses' => 'Claim\DataReportController@confirm']);

    Route::post('claims/{id}/processing/confirm', ['as' => 'claims.processing', 'uses' => 'ClaimsController@processing']);
    Route::post('claims/{id}/finished/confirm', ['as' => 'claims.finished', 'uses' => 'ClaimsController@finished']);

    // Insured claim view
    Route::get('/insured', ['as' => 'claims.public.login', 'uses' => 'ClaimsController@publicLogin']);
    Route::post('/insured', ['as' => 'claims.public.login', 'uses' => 'ClaimsController@postPublicLogin']);

    Route::resource('claims', 'ClaimsController');
    Route::resource('claims.dataIke', 'Claim\DataIkeController');
    Route::resource('claims.dataContact', 'Claim\DataContactController');
    Route::resource('claims.dataVerification', 'Claim\DataVerificationController');
    Route::resource('claims.dataVisits', 'Claim\DataVisitsController');
    Route::resource('claims.dataPreliminary', 'Claim\DataPreliminaryController');
    Route::resource('claims.dataReport', 'Claim\DataReportController');
    Route::resource('claims.damageAssessment', 'Claim\DamageAssessmentController');
    Route::resource('claims.contacts', 'Claim\ContactsController');
    Route::resource('claims.notes', 'Claim\NotesController');
    Route::resource('claims.documents', 'Claim\DocumentsController');
    Route::resource('claims.addresses', 'Claim\AddressesController');
    Route::resource('claims.surveys', 'Claim\SurveysController');
    Route::resource('claims.checkList', 'Claim\CheckListAnswersController');
    Route::resource('claims.statuses', 'Claim\StatusesController', ['only' => 'store']);

    // Stats
    Route::get('stats/users', ['as' => 'stats.users', 'uses' => 'StatsController@users' ]);
    Route::get('stats/external', ['as' => 'stats.external', 'uses' => 'StatsController@external' ]);
    Route::get('stats/get-claims', ['as' => 'stats.get-claims', 'uses' => 'StatsController@getClaims' ]);
    Route::get('stats/claims-cities', ['as' => 'stats.claims-cities', 'uses' => 'StatsController@claimsByCities' ]);
    Route::get('stats/claims-stats', ['as' => 'stats.claims-stats', 'uses' => 'StatsController@claimsStats' ]);
    Route::resource('stats', 'StatsController');
});

// Dashboard
Route::get('dashboard', ['as' => 'dashboard.index', 'uses' => 'DashboardController@getIndex']);

// Authentication routes...
Route::get('auth/logout', ['as' => 'auth.logout', 'uses' => 'Auth\AuthController@getLogout']);
Route::get('/', ['as' => 'auth.login', 'uses' => 'Auth\AuthController@getLogin']);
Route::post('/', ['as' => 'auth.login', 'uses' => 'Auth\AuthController@postLogin']);

// Insured claim view
Route::get('/insured', ['as' => 'public.login', 'uses' => 'Resources\PublicClaimsController@publicLogin']);
Route::post('/insured', ['as' => 'public.login', 'uses' => 'Resources\PublicClaimsController@postPublicLogin']);
Route::get('/insured/{hash}', ['as' => 'public.index', 'uses' => 'Resources\PublicClaimsController@publicClaim']);

laravel/app/Http/Controllers/Resources/Claim/AddressesController.php
<?php

namespace App\Http\Controllers\Resources\Claim;

use App\Events\ClaimWasUpdated;
use App\Http\Requests\Claim\AddressesStorePostRequest;
use App\Models\Address;
use App\Models\Claim;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class AddressesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param AddressesStorePostRequest|Request $request
     * @param $claimId
     * @return \Illuminate\Http\Response
     */
    public function store(AddressesStorePostRequest $request, $claimId)
    {
        $claim = Claim::findOrFail($claimId);

        // Store Address
        $address = new Address($request->input('claim.address'));
        $claim->address()->save($address);

        // Fire event
        // event(new ClaimWasUpdated($claim));

        return back()->with('messages.success', [trans('global.The address has been saved successfully')]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param AddressesStorePostRequest|Request $request
     * @param $claimId
     * @param $addressId
     * @return \Illuminate\Http\Response
     * @internal param int $id
     */
    public function update(AddressesStorePostRequest $request, $claimId, $addressId)
    {
        // Get Claim
        $claim = Claim::findOrFail($claimId);

        // Get Address
        $address = Address::findOrFail($addressId);

        // Update Address
        $address->fill($request->input('claim.address'));

        // Save Address
        $claim->address()->save($address);

        event(new ClaimWasUpdated($claim, ['type' => 'address', 'value' => $address]));

        return back()->with('messages.success', [trans('global.The address has been updated successfully')]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

laravel/app/Http/Controllers/Resources/Claim/CheckListAnswersController.php
<?php

namespace App\Http\Controllers\Resources\Claim;

use App\Models\CheckListAnswer;
use App\Models\Claim;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class CheckListAnswersController extends Controller
{
    /**
     * Store a newly created resource in storage.
     *
     * @param AddressesStorePostRequest|Request $request
     * @param $claimId
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, $claimId)
    {
        // Get Claim
        $claim = Claim::findOrFail($claimId);

        // Parse Date
        $answers = $request->input('claim.check_list');

        if (count($answers) == \App\Models\CheckListQuestion::all()->count()) {
            \DB::table('check_list_answers')->where('claim_id', $claim->id)->delete();
            foreach ($answers as $questionId => $answer) {
                $a = new CheckListAnswer(['claim_id' => $claim->id, 'question_id' => $questionId, 'answer' => $answer]);
                $claim->checkListAnswers()->save($a);
            }
            return back()->with('messages.success', [trans('global.The survey has been saved successfully')]);
        }
        else {
            return back()->with('messages.success', [trans('global.Missing data')]);
        }
    }
}

laravel/app/Http/Controllers/Resources/Claim/ContactsController.php
<?php

namespace App\Http\Controllers\Resources\Claim;

use App\Events\ClaimWasUpdated;
use App\Http\Requests\Claim\ContactsStorePostRequest;
use App\Http\Requests\Claim\ContactsUpdatePostRequest;
use App\Models\Claim;
use App\Models\Contact;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class ContactsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @param $claimId
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, $claimId)
    {
        $claim = Claim::findOrFail($claimId);

        // Store Contact
        $contact = new Contact($request->input('claim.contact'));
        $claim->contacts()->save($contact);

        // Fire event
        event(new ClaimWasUpdated($claim, ['type' => 'contact', 'value' => $contact, 'add' => TRUE]));

        return back()->with('messages.success', [trans('global.The contact has been created successfully')]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $claimId
     * @param  int $contactId
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $claimId, $contactId)
    {
        // Get Claim
        $claim = Claim::findOrFail($claimId);

        // Get Contact
        $contact = Contact::findOrFail($contactId);
        $contact->fill($request->input('claim.contact'));

        // Store Contact
        $claim->contacts()->save($contact);

        // Fire event
        event(new ClaimWasUpdated($claim, ['type' => 'contact', 'value' => $contact]));

        return back()->with('messages.success', [trans('global.The contact has been updated successfully')]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

laravel/app/Http/Controllers/Resources/Claim/DamageAssessmentController.php
<?php

namespace App\Http\Controllers\Resources\Claim;

use App\Models\Claim;
use App\Models\DamageAssessment;
use App\Models\Status;
use App\Models\Activity;
use Illuminate\Http\Request;
use Carbon\Carbon;
use Illuminate\Support\Facades\Auth;
use App\Events\ClaimWasUpdated;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class DamageAssessmentController extends Controller
{
    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @param $claimId
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, $claimId)
    {
        // Validate
        $this->validate($request, [
            'claim.damage_assessment.amount_loss' => ['required'],
            'claim.damage_assessment.deductible' => ['required'],
            'claim.damage_assessment.adjustment_description' => ['required'],
        ]);

        // Get Claim
        $claim = Claim::findOrFail($claimId);

        // Parse Data
        $damageAssessmentData = $request->input('claim.damage_assessment');
        $amount_loss = str_replace(',','.',$damageAssessmentData['amount_loss']);
        $deductible = str_replace(',','.',$damageAssessmentData['deductible']);
        $damageAssessmentData['amount_loss'] = $amount_loss;
        $damageAssessmentData['deductible'] = $deductible;
        $claim->damageAssessments()->save(new DamageAssessment($damageAssessmentData));

        // If a damage assessment is added after the report
        // has been confirmed, notify it with an activity
        if ($claim->status->id >= Status::REPORT) {
            event(new ClaimWasUpdated($claim, ['type' => 'damage assessment', 'add' => TRUE]));
        }

        return back()->with('messages.success', [trans('global.The damage assessment has been saved successfully')]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request $request
     * @param  int $claimId
     * @param  int $damageAssessmentId
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $claimId, $damageAssessmentId)
    {
        // Validate
        $this->validate($request, [
            'claim.damage_assessment.amount_loss' => ['required'],
            'claim.damage_assessment.deductible' => ['required'],
            'claim.damage_assessment.adjustment_description' => ['required'],
        ]);

        // Get Claim
        $claim = Claim::findOrFail($claimId);
        $damageAssessment = DamageAssessment::findOrFail($damageAssessmentId);

        // Parse Data
        $damageAssessmentData = $request->input('claim.damage_assessment');
        $damageAssessment->fill($damageAssessmentData);
        $claim->damageAssessments()->save($damageAssessment);

        // If a damage assessment is updated after the report
        // has been confirmed, notify it with an activity
        if ($claim->status->id >= Status::REPORT) {
            event(new ClaimWasUpdated($claim, ['type' => 'damage assessment']));
        }

        return back()->with('messages.success', [trans('global.The damage assessment has been updated successfully')]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request $request
     * @param  int $claimId
     * @param  int $damageAssessmentId
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $claimId, $damageAssessmentId)
    {
        // Get Claim
        $claim = Claim::findOrFail($claimId);
        $damageAssessment = DamageAssessment::findOrFail($damageAssessmentId);
        $damageAssessment->delete();

        // If a damage assessment is updated after the report
        // has been confirmed, notify it with an activity
        if ($claim->status->id >= Status::REPORT) {
            event(new ClaimWasUpdated($claim, ['type' => 'damage assessment', 'delete' => TRUE]));
        }

        return back()->with('messages.success', [trans('global.The damage assessment has been deleted successfully')]);
    }
}

laravel/app/Http/Controllers/Resources/Claim/DataContactController.php
<?php

namespace App\Http\Controllers\Resources\Claim;

use App\Events\ClaimVisitDateWasSet;
use App\Http\Requests\Claim\AddressesStorePostRequest;
use App\Models\Claim;
use App\Models\DataContact;
use App\Models\Activity;
use App\Models\Status;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class DataContactController extends Controller
{
    /**
     * Store a newly created resource in storage.
     *
     * @param AddressesStorePostRequest|Request $request
     * @param $claimId
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, $claimId)
    {
        // Validate
        $this->validate($request, [
            'claim.contact.contact' => ['required', 'in:yes,no'],
            'claim.contact.visit_date' => ['required', 'date_format:d/m/Y H:i'],
            'claim.contact.note' => ['required'],
        ]);

        // Get Claim
        $claim = Claim::findOrFail($claimId);

        // Parse Date
        $inputContact = $request->input('claim.contact');

        $date = Carbon::createFromFormat('d/m/Y H:i', $inputContact['visit_date']);
        $inputContact = array_merge($inputContact, ['visit_date' => $date]);

        // Store Ike
        $dataContact = new DataContact($inputContact);
        $claim->dataContact()->save($dataContact);

        // Create Activity
        $activity = new Activity([
            'activity' => 'contact',
            'date' => Carbon::now(),
            'attachment' => $dataContact->id,
            'claim_id' => $claim->id,
            'user_id' => Auth::user()->id]);
        $claim->activities()->save($activity);

        // Fire event
        if ($inputContact['contact'] == 'yes') {
            if ($claim->status->id == Status::VERIFICATION) {
                $status = Status::find(Status::CONTACT);
                $claim->statuses()->save($status);

                $claim->last_status = $status->id;
                $claim->save();
            }
        }

        return back()->with('messages.success', [trans('global.The contact data has been saved successfully')]);
    }
}

laravel/resources/views/resources/claims/data_verification/create.blade.php
@extends('resources.claims.data_verification.modal', [
    'action' => route('claims.dataVerification.store', [$claim])
])

@section('form-data-verification')
    @include('resources.claims.data_verification.form', [
        'dataVerification' => [
            'policy_payment' => old('claim.data_verification.policy_payment', ''),
            'validity_start' => old('claim.data_verification.validity_start', ''),
            'validity_end' => old('claim.data_verification.validity_end', ''),
            'siu' => old('claim.data_verification.siu', ''),
            'coinsurance' => old('claim.data_verification.coinsurance', ''),
            'complaint' => old('claim.data_verification.complaint', ''),
            'analyst_id' => old('claim.data_verification.analyst_id', ''),
            'coinsurance_company' => old('claim.data_verification.coinsurance_company', ''),
            'coinsurance_percentage' => old('claim.data_verification.coinsurance_percentage', ''),
        ]
    ])
@endsection

laravel/resources/views/resources/claims/data_verification/edit.blade.php
@extends('resources.claims.data_verification.modal', [
    'action' => route('claims.dataVerification.update', [$claim, $claim->dataVerification])
])

@section('form-data-verification')
    {!! method_field('PUT') !!}
    @include('resources.claims.data_verification.form', [
        'dataVerification' => old('claim.data_verification') ? old('claim.data_verification') : $claim->dataVerification->toArray()
    ])
@endsection

laravel/resources/views/resources/claims/data_verification/index.blade.php
<div class="panel panel-default">
    <div class="panel-heading">
        {!! trans('global.Claim Verification') !!}

        @if($editable && $claim->canBeVerified())
            <div class="panel-options">
                <form method="POST" action="{!! route('claims.statuses.store', $claim) !!}" style="display:inline-block">
                    {!! csrf_field() !!}
                    <input type="hidden" name="status_id" value="{!! \App\Models\Status::CONTACT !!}">
                    <button class="btn btn-single btn-success {!! $claim->isDataVerificationComplete() ? '' : 'disabled' !!}">{!! trans('global.Approve Claim') !!}</button>
                </form>
                <button class="btn btn-single btn-danger"
                        data-toggle="modal"
                        data-target="#modal-claims-cancel">{!! trans('global.Cancel Claim') !!}
                </button>
            </div>
        @endif

    </div>
    <div class="panel-body">
        @if(!empty($claim->dataVerification->id))
            @include('resources.claims.data_verification.edit', [
                'claimAttributes' => [
                    'zurich_claim_number' => $claim->zurich_claim_number != null ? $claim->zurich_claim_number : '' ,
                    'is_cover_correct' => $claim->is_cover_correct != null ? $claim->is_cover_correct : ''
                ]
            ])
        @else
            @include('resources.claims.data_verification.create', [
                'claimAttributes' => [
                    'zurich_claim_number' => '',
                    'is_cover_correct' => null
                ]
            ])
        @endif
    </div>
    @include('resources.claims.data_verification.modal-claim-cancel')
</div>

laravel/resources/views/resources/claims/data_verification/modal-claim-cancel.blade.php
<div class="modal fade" id="modal-claims-cancel">
    <div class="modal-dialog">
        <div class="modal-content">

            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">{!! trans('global.Are you sure?') !!}</h4>
            </div>

            <div class="modal-body">
                {!! trans('global.Are you sure you want to cancel this claim?') !!}
            </div>

            <div class="modal-footer">
                <form action="{!! route('claims.statuses.store', $claim) !!}" method="POST">
                    {!! csrf_field() !!}
                    <input  type="hidden" name="status_id" value="{!! \App\Models\Status::CANCELLED !!}">
                    <button type="button" class="btn btn-white" data-dismiss="modal">
                        {!! trans('global.Close') !!}
                    </button>
                    <button type="submit" class="btn btn-danger">
                        {!! trans('global.Cancel Claim') !!}
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>

laravel/resources/views/resources/claims/data_verification/modal.blade.php
<form role="form" method="POST" action="{!! $action !!}" class="validate" novalidate>
    {!! csrf_field() !!}
    @yield('form-data-verification')
</form>

laravel/resources/views/resources/claims/data_verification/show.blade.php
@if(!empty($claim->dataIke->id))
    @include('resources.claims.data_ike.form', [
        'disabled' => true,
        'ike' => $claim->dataIke->toArray()
    ])
@else
    <div class="alert alert-danger">{!! trans('global.No data provided') !!}</div>
@endif