laravel/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

/* Api */
Route::group(['prefix' => 'api', 'namespace' => 'Api'], function () {
    // Users
    Route::controller('geo-location', 'GeoLocationController');
});

/* Resources */
Route::group(['namespace' => 'Resources'], function () {
    // Users
    Route::resource('users', 'UsersController');

    // Claims

    Route::post('claims/{id}/update-info', ['as' => 'claims.update-info', 'uses' => 'ClaimsController@updateInfo']);
    Route::post('claims/{id}/update-description', ['as' => 'claims.update-description', 'uses' => 'ClaimsController@updateDescription']);
    Route::post('claims/{id}/update-ike', ['as' => 'claims.update-ike', 'uses' => 'ClaimsController@updateIke']);

    Route::get('claims/{id}/{status}', ['as' => 'claims.status', 'uses' => 'ClaimsController@show']);

    Route::post('claims/{id}/verification/approve', ['as' => 'claims.dataVerification.approve', 'uses' => 'Claim\DataVerificationController@approve']);
    Route::post('claims/{id}/verification/cancel', ['as' => 'claims.dataVerification.cancel', 'uses' => 'Claim\DataVerificationController@cancel']);

    Route::post('claims/{id}/report/confirm', ['as' => 'claims.dataReport.confirm', 'uses' => 'Claim\DataReportController@confirm']);

    Route::post('claims/{id}/processing/confirm', ['as' => 'claims.processing', 'uses' => 'ClaimsController@processing']);
    Route::post('claims/{id}/finished/confirm', ['as' => 'claims.finished', 'uses' => 'ClaimsController@finished']);

    // Insured claim view
    Route::get('/insured', ['as' => 'claims.public.login', 'uses' => 'ClaimsController@publicLogin']);
    Route::post('/insured', ['as' => 'claims.public.login', 'uses' => 'ClaimsController@postPublicLogin']);

    Route::resource('claims', 'ClaimsController');
    Route::resource('claims.dataIke', 'Claim\DataIkeController');
    Route::resource('claims.dataContact', 'Claim\DataContactController');
    Route::resource('claims.dataVerification', 'Claim\DataVerificationController');
    Route::resource('claims.dataVisits', 'Claim\DataVisitsController');
    Route::resource('claims.dataPreliminary', 'Claim\DataPreliminaryController');
    Route::resource('claims.dataReport', 'Claim\DataReportController');
    Route::resource('claims.damageAssessment', 'Claim\DamageAssessmentController');
    Route::resource('claims.contacts', 'Claim\ContactsController');
    Route::resource('claims.notes', 'Claim\NotesController');
    Route::resource('claims.documents', 'Claim\DocumentsController');
    Route::resource('claims.addresses', 'Claim\AddressesController');
    Route::resource('claims.surveys', 'Claim\SurveysController');
    Route::resource('claims.checkList', 'Claim\CheckListAnswersController');
    Route::resource('claims.statuses', 'Claim\StatusesController', ['only' => 'store']);

    // Stats
    Route::get('stats/users', ['as' => 'stats.users', 'uses' => 'StatsController@users' ]);
    Route::get('stats/external', ['as' => 'stats.external', 'uses' => 'StatsController@external' ]);
    Route::get('stats/get-claims', ['as' => 'stats.get-claims', 'uses' => 'StatsController@getClaims' ]);
    Route::get('stats/claims-cities', ['as' => 'stats.claims-cities', 'uses' => 'StatsController@claimsByCities' ]);
    Route::get('stats/claims-stats', ['as' => 'stats.claims-stats', 'uses' => 'StatsController@claimsStats' ]);
    Route::resource('stats', 'StatsController');
});

// Dashboard
Route::get('dashboard', ['as' => 'dashboard.index', 'uses' => 'DashboardController@getIndex']);

// Authentication routes...
Route::get('auth/logout', ['as' => 'auth.logout', 'uses' => 'Auth\AuthController@getLogout']);
Route::get('/', ['as' => 'auth.login', 'uses' => 'Auth\AuthController@getLogin']);
Route::post('/', ['as' => 'auth.login', 'uses' => 'Auth\AuthController@postLogin']);

// Insured claim view
Route::get('/insured', ['as' => 'public.login', 'uses' => 'Resources\PublicClaimsController@publicLogin']);
Route::post('/insured', ['as' => 'public.login', 'uses' => 'Resources\PublicClaimsController@postPublicLogin']);
Route::get('/insured/{hash}', ['as' => 'public.index', 'uses' => 'Resources\PublicClaimsController@publicClaim']);

laravel/app/Http/Controllers/Resources/Claim/AddressesController.php
<?php

namespace App\Http\Controllers\Resources\Claim;

use App\Events\ClaimWasUpdated;
use App\Http\Requests\Claim\AddressesStorePostRequest;
use App\Models\Address;
use App\Models\Claim;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class AddressesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param AddressesStorePostRequest|Request $request
     * @param $claimId
     * @return \Illuminate\Http\Response
     */
    public function store(AddressesStorePostRequest $request, $claimId)
    {
        $claim = Claim::findOrFail($claimId);

        // Store Address
        $address = new Address($request->input('claim.address'));
        $claim->address()->save($address);

        // Fire event
        // event(new ClaimWasUpdated($claim));

        return back()->with('messages.success', [trans('global.The address has been saved successfully')]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param AddressesStorePostRequest|Request $request
     * @param $claimId
     * @param $addressId
     * @return \Illuminate\Http\Response
     * @internal param int $id
     */
    public function update(AddressesStorePostRequest $request, $claimId, $addressId)
    {
        // Get Claim
        $claim = Claim::findOrFail($claimId);

        // Get Address
        $address = Address::findOrFail($addressId);

        // Update Address
        $address->fill($request->input('claim.address'));

        // Save Address
        $claim->address()->save($address);

        event(new ClaimWasUpdated($claim, ['type' => 'address', 'value' => $address]));

        return back()->with('messages.success', [trans('global.The address has been updated successfully')]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

laravel/app/Http/Controllers/Resources/Claim/CheckListAnswersController.php
<?php

namespace App\Http\Controllers\Resources\Claim;

use App\Models\CheckListAnswer;
use App\Models\Claim;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class CheckListAnswersController extends Controller
{
    /**
     * Store a newly created resource in storage.
     *
     * @param AddressesStorePostRequest|Request $request
     * @param $claimId
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, $claimId)
    {
        // Get Claim
        $claim = Claim::findOrFail($claimId);

        // Parse Date
        $answers = $request->input('claim.check_list');

        if (count($answers) == \App\Models\CheckListQuestion::all()->count()) {
            \DB::table('check_list_answers')->where('claim_id', $claim->id)->delete();
            foreach ($answers as $questionId => $answer) {
                $a = new CheckListAnswer(['claim_id' => $claim->id, 'question_id' => $questionId, 'answer' => $answer]);
                $claim->checkListAnswers()->save($a);
            }
            return back()->with('messages.success', [trans('global.The survey has been saved successfully')]);
        }
        else {
            return back()->with('messages.success', [trans('global.Missing data')]);
        }
    }
}

laravel/app/Http/Controllers/Resources/Claim/ContactsController.php
<?php

namespace App\Http\Controllers\Resources\Claim;

use App\Events\ClaimWasUpdated;
use App\Http\Requests\Claim\ContactsStorePostRequest;
use App\Http\Requests\Claim\ContactsUpdatePostRequest;
use App\Models\Claim;
use App\Models\Contact;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class ContactsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @param $claimId
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, $claimId)
    {
        $claim = Claim::findOrFail($claimId);

        // Store Contact
        $contact = new Contact($request->input('claim.contact'));
        $claim->contacts()->save($contact);

        // Fire event
        event(new ClaimWasUpdated($claim, ['type' => 'contact', 'value' => $contact, 'add' => TRUE]));

        return back()->with('messages.success', [trans('global.The contact has been created successfully')]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $claimId
     * @param  int $contactId
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $claimId, $contactId)
    {
        // Get Claim
        $claim = Claim::findOrFail($claimId);

        // Get Contact
        $contact = Contact::findOrFail($contactId);
        $contact->fill($request->input('claim.contact'));

        // Store Contact
        $claim->contacts()->save($contact);

        // Fire event
        event(new ClaimWasUpdated($claim, ['type' => 'contact', 'value' => $contact]));

        return back()->with('messages.success', [trans('global.The contact has been updated successfully')]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

laravel/app/Http/Controllers/Resources/Claim/DamageAssessmentController.php
<?php

namespace App\Http\Controllers\Resources\Claim;

use App\Models\Claim;
use App\Models\DamageAssessment;
use App\Models\Status;
use App\Models\Activity;
use Illuminate\Http\Request;
use Carbon\Carbon;
use Illuminate\Support\Facades\Auth;
use App\Events\ClaimWasUpdated;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class DamageAssessmentController extends Controller
{
    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @param $claimId
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, $claimId)
    {
        // Validate
        $this->validate($request, [
            'claim.damage_assessment.amount_loss' => ['required'],
            'claim.damage_assessment.deductible' => ['required'],
            'claim.damage_assessment.adjustment_description' => ['required'],
        ]);

        // Get Claim
        $claim = Claim::findOrFail($claimId);

        // Parse Data
        $damageAssessmentData = $request->input('claim.damage_assessment');
        $amount_loss = str_replace(',','.',$damageAssessmentData['amount_loss']);
        $deductible = str_replace(',','.',$damageAssessmentData['deductible']);
        $damageAssessmentData['amount_loss'] = $amount_loss;
        $damageAssessmentData['deductible'] = $deductible;
        $claim->damageAssessments()->save(new DamageAssessment($damageAssessmentData));

        // If a damage assessment is added after the report
        // has been confirmed, notify it with an activity
        if ($claim->status->id >= Status::REPORT) {
            event(new ClaimWasUpdated($claim, ['type' => 'damage assessment', 'add' => TRUE]));
        }

        return back()->with('messages.success', [trans('global.The damage assessment has been saved successfully')]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request $request
     * @param  int $claimId
     * @param  int $damageAssessmentId
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $claimId, $damageAssessmentId)
    {
        // Validate
        $this->validate($request, [
            'claim.damage_assessment.amount_loss' => ['required'],
            'claim.damage_assessment.deductible' => ['required'],
            'claim.damage_assessment.adjustment_description' => ['required'],
        ]);

        // Get Claim
        $claim = Claim::findOrFail($claimId);
        $damageAssessment = DamageAssessment::findOrFail($damageAssessmentId);

        // Parse Data
        $damageAssessmentData = $request->input('claim.damage_assessment');
        $damageAssessment->fill($damageAssessmentData);
        $claim->damageAssessments()->save($damageAssessment);

        // If a damage assessment is updated after the report
        // has been confirmed, notify it with an activity
        if ($claim->status->id >= Status::REPORT) {
            event(new ClaimWasUpdated($claim, ['type' => 'damage assessment']));
        }

        return back()->with('messages.success', [trans('global.The damage assessment has been updated successfully')]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request $request
     * @param  int $claimId
     * @param  int $damageAssessmentId
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $claimId, $damageAssessmentId)
    {
        // Get Claim
        $claim = Claim::findOrFail($claimId);
        $damageAssessment = DamageAssessment::findOrFail($damageAssessmentId);
        $damageAssessment->delete();

        // If a damage assessment is updated after the report
        // has been confirmed, notify it with an activity
        if ($claim->status->id >= Status::REPORT) {
            event(new ClaimWasUpdated($claim, ['type' => 'damage assessment', 'delete' => TRUE]));
        }

        return back()->with('messages.success', [trans('global.The damage assessment has been deleted successfully')]);
    }
}

laravel/app/Http/Controllers/Resources/Claim/DataContactController.php
<?php

namespace App\Http\Controllers\Resources\Claim;

use App\Events\ClaimVisitDateWasSet;
use App\Http\Requests\Claim\AddressesStorePostRequest;
use App\Models\Claim;
use App\Models\DataContact;
use App\Models\Activity;
use App\Models\Status;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class DataContactController extends Controller
{
    /**
     * Store a newly created resource in storage.
     *
     * @param AddressesStorePostRequest|Request $request
     * @param $claimId
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, $claimId)
    {
        // Validate
        $this->validate($request, [
            'claim.contact.contact' => ['required', 'in:yes,no'],
            'claim.contact.visit_date' => ['required', 'date_format:d/m/Y H:i'],
            'claim.contact.note' => ['required'],
        ]);

        // Get Claim
        $claim = Claim::findOrFail($claimId);

        // Parse Date
        $inputContact = $request->input('claim.contact');

        $date = Carbon::createFromFormat('d/m/Y H:i', $inputContact['visit_date']);
        $inputContact = array_merge($inputContact, ['visit_date' => $date]);

        // Store Ike
        $dataContact = new DataContact($inputContact);
        $claim->dataContact()->save($dataContact);

        // Create Activity
        $activity = new Activity([
            'activity' => 'contact',
            'date' => Carbon::now(),
            'attachment' => $dataContact->id,
            'claim_id' => $claim->id,
            'user_id' => Auth::user()->id]);
        $claim->activities()->save($activity);

        // Fire event
        if ($inputContact['contact'] == 'yes') {
            if ($claim->status->id == Status::VERIFICATION) {
                $status = Status::find(Status::CONTACT);
                $claim->statuses()->save($status);

                $claim->last_status = $status->id;
                $claim->save();
            }
        }

        return back()->with('messages.success', [trans('global.The contact data has been saved successfully')]);
    }
}

laravel/resources/views/resources/claims/addresses/create.blade.php
@extends('resources.claims.addresses.modal', [
    'action' => route('claims.addresses.store', [$claim])
])

@section('modal-body')
    @include('resources.claims.addresses.form', [
        'claimAddress' => old('claim.address')
    ])
@endsection

laravel/resources/views/resources/claims/addresses/edit.blade.php
@extends('resources.claims.addresses.modal', [
    'action' => route('claims.addresses.update', [$claim, $claim->address])
])

@section('modal-body')
    {!! method_field('PUT') !!}
    @include('resources.claims.addresses.form', [
        'claimAddress' => old('claim.address') ? old('claim.address') : $claim->address->toArray()
    ])
@endsection

laravel/resources/views/resources/claims/addresses/form.blade.php
<div class="row">

    <div class="col-md-12">
        <div class="form-group {!! $errors->first('claim.address.address') ? 'has-error' : '' !!}">
            <label class="control-label" for="street">{!! trans('global.Address') !!}</label>
            <input class="form-control" name="claim[address][address]" id="street" data-validate="required"
                   placeholder="{!! trans('global.Address') !!}"
                   value="{!! $claimAddress['address'] !!}"
                    {!! !empty($disabled) ? 'disabled' : '' !!}
                    />
        </div>
    </div>

</div>


<div class="row">

    <div class="col-md-4">
        <div class="form-group {!! $errors->first('claim.address.country_id') ? 'has-error' : '' !!}">
            <label for="state">{!! trans('global.Country') !!}</label>
            <select id="country" name="claim[address][country_id]" class="form-control" data-validate="required" {!! !empty($disabled) ? 'disabled' : '' !!}>
                <option value="">{!! trans('global.Select Country') !!}</option>
                @foreach($countries as $country)
                    <?php
                    $selected = $claimAddress['country_id'] == $country->id  ? 'selected' : '';
                    if ($selected == 'selected')
                        $countryName = $country->name;
                    ?>
                    <option value="{!! $country->id !!}" {!! $selected !!}>{!! $country->name !!}</option>
                @endforeach
            </select>
        </div>
    </div>

    <div class="col-md-4">
        <div class="form-group {!! $errors->first('claim.address.state_id') ? 'has-error' : '' !!}">
            <label for="state">{!! trans('global.State') !!}</label>
            <select id="state" name="claim[address][state_id]" class="form-control" data-validate="required" {!! !empty($disabled) ? 'disabled' : '' !!}>
                <option value="">{!! trans('global.Select State') !!}</option>
                @if(!empty($selectedCountry))
                    @foreach($selectedCountry->states as $state)
                        <?php
                        $selected = $claimAddress['state_id'] == $state->id  ? 'selected' : '';
                        if ($selected == 'selected')
                            $stateName = $state->name;
                        ?>
                        <option value="{!! $state->id !!}" {!! $selected !!}>{!! $state->name !!}</option>
                    @endforeach
                @endif
            </select>
        </div>
    </div>

    <div class="col-md-4">
        <div class="form-group">
            <label for="state">{!! trans('global.City') !!}</label>

            <select id="city" name="claim[address][city_id]" class="form-control" {!! !empty($disabled) ? 'disabled' : '' !!}>
                <option value="">{!! trans('global.Select City') !!}</option>
                @if(!empty($selectedState))
                    @foreach($selectedState->cities as $city)
                        <?php
                        $selected = $claimAddress['city_id'] == $city->id  ? 'selected' : '';
                        if ($selected == 'selected')
                            $cityName = $city->name;
                        ?>
                        <option value="{!! $city->id !!}" {!! $selected !!}>{!! $city->name !!}</option>
                    @endforeach
                @endif
            </select>
        </div>
    </div>

</div>


<div class="row">

    <div class="col-md-12">
        <div id="address-map-container" class="hidden">
            <label for="state">{!! trans('global.Map') !!}</label>
            <div id="addressMap"></div>
        </div>
    </div>

</div>
<script src="https://maps.googleapis.com/maps/api/js"></script>
<script>
    function initialize(myLatLng) {

        // Create a map object and specify the DOM element for display.
        var map = new google.maps.Map(document.getElementById('addressMap'), {
            center: myLatLng,
            scrollwheel: false,
            zoom: 12
        });

        // Create a marker and set its position.
        var marker = new google.maps.Marker({
            map: map,
            position: myLatLng,
            title: 'Hello World!'
        });

        $('#address-map-container').removeClass('hidden');
    }

    function generateMapFromAddress(address) {
        var url = "http://maps.googleapis.com/maps/api/geocode/json?address=" + address + "&sensor=false";
        $.getJSON(url)
                .done(function (data) {
                    if (data.results.length > 0) {
                        var location = data.results[0].geometry.location;
                        initialize({'lat': parseFloat(location.lat), 'lng': parseFloat(location.lng)});
                    }
                    else {
                        console.log('no results');
                        $('#address-map-container').addClass('hidden');
                    }
                })
                .fail(function () {
                    console.log("error on address map");
                });
    }
</script>

@if(isset($claimAddress['address']))
    <?php
    $address = str_replace (" ", "+", str_replace ("\n", "+", $claimAddress['address']));
    if (!isset($cityName)) {
        $cityName = '';
    }
    $finalAddress = $address . ',+' . $cityName . ',+' . $stateName . ',+' . $countryName;
    ?>
    <script>
        var address = "{!! $finalAddress !!}";
        generateMapFromAddress(address);
    </script>
@else
    <script>
        function getAddress() {
            var street = $('#street').val();
            var country = '';
            var state = '';
            var city = '';

            if($('#country').val() != '') {
                country = ', ' + $('#country').find(":selected").text();
            }
            if($('#state').val() != '') {
                state = ', ' + $('#state').find(":selected").text();
            }
            if($('#city').val() != '') {
                city = ', ' + $('#city').find(":selected").text();
            }

            var address = street + city + state + country;
            return address;
        }

        function generate() {
            var address = getAddress();
            if(address != '') {
                generateMapFromAddress(address.replace(/\s+/g, '+'));
            }
            else {
                $('#address-map-container').addClass('hidden');
            }
        }

        // Update with every change
        $('#street').focusout(generate);
        $("select[name^='claim[address]']").change(generate);

        // Generates map only when all fields are complete
        //        $("[name^='claim[address]").change(function(){
        //            if( $('#street').val() != '' && ($('#country').val() != '') && ($('#state').val() != '') && ($('#city').val() != '')) {
        //                generate();
        //            }
        //        });

    </script>
@endif

laravel/resources/views/resources/claims/addresses/index.blade.php
<div class="panel panel-default">
    <div class="panel-heading">
        {!! trans('global.Claim Address') !!}
        @if($editable)
            <div class="panel-options">
                <a class="btn btn-single btn-gray" data-toggle="modal" data-target="#modal-claims-address">Edit</a>
            </div>
        @endif
    </div>

    <div class="panel-body">

        <!-- Show -->
        @include('resources.claims.addresses.show')

        <!-- Modal -->
        @if(!empty($claim->address->id))
            @include('resources.claims.addresses.edit')
        @else
            @include('resources.claims.addresses.create')
        @endif
    </div>
</div>

laravel/resources/views/resources/claims/addresses/modal.blade.php
<div class="modal {!! old('modal_old') == 'modal-claims-address' ? 'modal_old' : '' !!}" id="modal-claims-address">
    <div class="modal-dialog">
        <div class="modal-content">

            <form role="form" method="POST" action="{!! $action !!}" class="validate" novalidate>
                {!! csrf_field() !!}
                <input type="hidden" name="modal_old" value="modal-claims-address">

                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">{!! trans('global.Edit Claim Information') !!}</h4>
                </div>

                <div class="modal-body">
                    @yield('modal-body')
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-white" data-dismiss="modal">
                        {!! trans('global.Close') !!}
                    </button>
                    <button type="submit" class="btn btn-success">
                        {!! trans('global.Save') !!}
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

laravel/resources/views/resources/claims/addresses/show.blade.php
@if(!empty($claim->address->id))
    @include('resources.claims.addresses.form', [
        'disabled' => true,
        'claimAddress' => $claim->address->toArray()
    ])
@else
    <div class="alert alert-danger">{!! trans('global.No data provided') !!}</div>
@endif

laravel/resources/views/resources/claims/addresses/table-list.blade.php
<table class="table table-hover members-table middle-align">
    <thead>
    <tr>
        <th></th>
        <th>{!! trans('global.Name') !!}</th>
        <th>{!! trans('global.Phone') !!}</th>
        <th>{!! trans('global.Email') !!}</th>
        <th>{!! trans('global.Options') !!}</th>
    </tr>
    </thead>
    <tbody>
    @foreach($addresses as $address)
        <tr>
            <td>
                {!! $address->id !!}
            </td>
            <td class="hidden-xs hidden-sm">
                <span class="email">{!! $user->email !!}</span>
            </td>
            <td class="user-id">
                {!! $user->id !!}
            </td>
            <td class="action-links">
                <a href="{!! route('users.edit', $user) !!}" class="edit">
                    <i class="linecons-pencil"></i>
                    {!! trans('global.Edit') !!}
                </a>

                <a href="javascript:" class="delete" data-toggle="modal" data-target="#modal-delete-user-{!! $user->id !!}">
                    <i class="linecons-trash"></i>
                    {!! trans('global.Delete') !!}
                </a>

                @include('modals.alert-delete', ['modalId' => 'delete-user-' . $user->id])

            </td>
        </tr>
    @endforeach
    </tbody>
</table>

<div class="row">
    <div class="col-sm-offset-6 col-sm-6 text-right text-center-sm">
        {!! $users->render() !!}
    </div>
</div>